alias :q="exit"
alias brightness="xrandr --output LVDS1 --brightness"
alias -g g=" | grep"
alias tixe=exit
alias sshtun="sshuttle --dns -D -x adjoint.fun -r googleson78@adjoint.fun 0.0.0.0/0"
alias destroystack="find -name '.stack-work' -exec rm -rf {} +"
alias chez=chezscheme9.5
alias vim=nvim
alias vi=nvim
